### ISSUE TITLE
Missing to find Babel on Windows

### ISSUE THREAD

**Issue by anaibol** [jumilla/atom-riot#2]
Hi, I am sadly using windows OS and having installed globally the Babel package, I am receiving this error trying to compile on save:
Error: Cannot find module 'babel' at Function.Module._resolveFilename

Do you know anything I can do?

Thanks!

**Comment by jumilla** [comment]
Hi @anaibol !

`atom-riot` was written ES6.

The error is, what error of the package itself? Or is error when you try to build on save a riot source?
If the first, I can solve soon.

**Comment by anaibol** [comment]
Hi! It's the second one, when trying to build on save a riot source.

**Comment by anaibol** [comment]
The issue is related with the es6 scripts, it's failing only with them

```
<catalog>
  <script type="es6">
    console.log(opts);
  </script>
</catalog>
```

**Comment by jumilla** [comment]
@anaibol OK,

Here is [Global riot path definition](https://github.com/jumilla/atom-riot/blob/master/lib/riot.es6#L10).

Do you know the riot command path that has been npm global installed in Windows?

**Comment by anaibol** [comment]
It's '%USERPROFILE%\AppData\Roaming\npm\riot'

I tryed with 
```
const RIOT_PATH = '%USERPROFILE%\\AppData\\Roaming\\npm\\riot'
```
but didn't worked

**Comment by jumilla** [comment]
Maybe need extract `%USERPROFILE%` variable in riot.es6.

**Comment by jumilla** [comment]
@anaibol We released atom-riot v0.3.0.

Support environment variable `RIOT_PATH`.
Please try it.

**Comment by jumilla** [comment]
@anaibol Hi!

v0.4.1: Support package setting 'Riot-CLI path'.

![2015-11-16 14 50 09](https://cloud.githubusercontent.com/assets/4950710/11175078/6b6acff2-8c71-11e5-91e6-001084a460e8.png)

Please try it.

**Comment by anaibol** [comment]
Hi, I am trying with or without custom Riot cli path, but there is no compilation or error. I think that Atom in general is not working properly on Windows.

**Comment by jumilla** [comment]
@anaibol 

Hi,
Do not work with the following settings?

Riot-CLI path: "C:\Users\AppData\Roaming\npm\riot"

Please error messages or screen shots.

**Comment by anaibol** [comment]
Mmm, I see no errors, neither the console.log of the path you put. Tried compiling on save and compiling via command.

![shot](https://cloud.githubusercontent.com/assets/3210177/11208957/72153308-8d1e-11e5-900f-a85c6736a7de.png)

**Comment by jumilla** [comment]
OK.

To execute the command, please the text editor view to active.

Click the text editor section, and run the command.

**Comment by anaibol** [comment]
Ohh it was the Atom grammar that was autosetted to JavaServer Pages.. I setted to HTML (Riot).

Now it fails to find Babel. Is it compatible with Babel 6?

![shot](https://cloud.githubusercontent.com/assets/3210177/11212425/066da08c-8d36-11e5-8e29-f386ce3ea662.png)

**Comment by jumilla** [comment]
Oh yeah! (^0^)/

I write the blog article (Japanese)
http://jumilla.me/atom-package-riot-updated-for-riot23

> Now it fails to find Babel. Is it compatible with Babel 6?

Please look at the issue.
https://github.com/riot/riot/issues/1339

**Comment by anaibol** [comment]
Perfect! Thanks man, great work!

**Comment by jumilla** [comment]
Good!
Thank you very much to me dating to the last!
